//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Surgical.SDK.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Surgical.SDK.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Banner {
            get {
                object obj = ResourceManager.GetObject("Banner", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;en&quot;: {
        ///    &quot;text&quot;: &quot;Surgical Evade&quot;
        ///  },
        ///  &quot;zh&quot;: {
        ///    &quot;text&quot;: &quot;??&quot; 
        ///  } 
        ///}
        ///.
        /// </summary>
        internal static string Evade {
            get {
                return ResourceManager.GetString("Evade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;en&quot;: {
        ///    &quot;text&quot;: &quot;Surgical SDK&quot;,
        ///    &quot;helpText&quot;: &quot;Here you will find all the settings that impact other scripts&quot;
        ///  },
        ///  &quot;zh&quot;: {
        ///    &quot;text&quot;: &quot;Surgeon制作&quot;,
        ///    &quot;helpText&quot;: &quot;帮助&quot;
        ///  },
        ///  &quot;language&quot;: {
        ///    &quot;en&quot;: {
        ///      &quot;text&quot;: &quot;Language&quot;
        ///    },
        ///    &quot;zh&quot;: {
        ///      &quot;text&quot;: &quot;语言 (language)&quot;
        ///    }
        ///  },
        ///  &quot;modes&quot;: {
        ///    &quot;en&quot;: {
        ///      &quot;text&quot;: &quot;Modes&quot;,
        ///      &quot;helpText&quot;: &quot;All the settings besides key are champion-specific&quot;
        ///    },
        ///    &quot;zh&quot;: {
        ///      &quot;text&quot;: &quot;SHANA PLS TRANSLATE TY&quot;
        ///    },
        ///     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MainMenu {
            get {
                return ResourceManager.GetString("MainMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;key&quot;: {
        ///    &quot;en&quot;: {
        ///      &quot;text&quot;: &quot;Activation key&quot;
        ///    },
        ///    &quot;zh&quot;: {
        ///      &quot;text&quot;: &quot;??&quot;
        ///    }
        ///  },
        ///  &quot;champSpells&quot;: {
        ///    &quot;en&quot;: {
        ///      &quot;text&quot;: &quot;Spell usage on champs&quot;,
        ///      &quot;options&quot;: [
        ///        &quot;Don&apos;t use spells&quot;,
        ///        &quot;Poke spells only&quot;,
        ///        &quot;All spells&quot;
        ///      ]
        ///    }
        ///  },
        ///  &quot;champAuto&quot;: {
        ///    &quot;en&quot;: {
        ///      &quot;text&quot;: &quot;Autoattack champions&quot; 
        ///    } 
        ///  },
        ///  &quot;minions&quot;: {
        ///    &quot;en&quot;: {
        ///      &quot;text&quot;: &quot;Minions&quot;,
        ///      &quot;options&quot;: [
        ///        &quot;Don&apos;t attack&quot;,
        ///        &quot;Lasthit&quot;,        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Mode {
            get {
                return ResourceManager.GetString("Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;en&quot;: {
        ///    &quot;text&quot;: &quot;{module}&quot;
        ///  },
        ///  &quot;zh&quot;: {
        ///    &quot;text&quot;: &quot;{module}&quot;
        ///  },
        ///  &quot;picker&quot;: {
        ///    &quot;en&quot;: {
        ///      &quot;text&quot;: &quot;Selected {module}&quot;,
        ///      &quot;helpText&quot;: &quot;{module} will be changed immediately&quot;
        ///    },
        ///    &quot;zh&quot;: {
        ///      &quot;text&quot;: &quot;ZH- Selected {module}&quot;,
        ///      &quot;helpText&quot;: &quot;ZH- {module} will be changed immediately&quot;
        ///    } 
        ///  } 
        ///}.
        /// </summary>
        internal static string Module {
            get {
                return ResourceManager.GetString("Module", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;en&quot;: {
        ///    &quot;text&quot;: &quot;Not implemented&quot;
        ///  },
        ///  &quot;zh&quot;: {
        ///    &quot;text&quot;: &quot;??&quot; 
        ///  } 
        ///}.
        /// </summary>
        internal static string NullChampion {
            get {
                return ResourceManager.GetString("NullChampion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;en&quot;: {
        ///    &quot;text&quot;:  &quot;Surgical&quot; 
        ///  }
        ///}.
        /// </summary>
        internal static string Orbwalker {
            get {
                return ResourceManager.GetString("Orbwalker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Picker {
            get {
                object obj = ResourceManager.GetObject("Picker", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] RenderEffectCompiled {
            get {
                object obj = ResourceManager.GetObject("RenderEffectCompiled", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;en&quot;: {
        ///    &quot;keySelector&quot;: &quot;Press now...&quot;,
        ///    &quot;firstTimeWelcome&quot;: &quot;Welcome to {platform}!\nEnglish language detected.\nYou can change that from within the menu.&quot;,
        ///    &quot;none&quot;: &quot;None&quot;,
        ///    &quot;platformHasNoTheme&quot;: &quot;has no theme&quot;,
        ///    &quot;loaderHeader&quot;: &quot;No new scripts detected&quot;,
        ///    &quot;loaderContent&quot;: &quot;In case of malfunctioning,\nplease make sure to put the .dll in\n%appdata%/Surgical.SDK/Scripts&quot;,
        ///
        ///    // special, don&apos;t translate
        ///    &quot;languageUnknown&quot;: &quot;Welcome to {platform}!\nYour system language,\n\ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Strings {
            get {
                return ResourceManager.GetString("Strings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;en&quot;: {
        ///    &quot;text&quot;: &quot;Surgical&quot;
        ///  },
        ///  &quot;zh&quot;: {
        ///    &quot;text&quot;: &quot;??&quot; 
        ///  },
        ///  &quot;timeToKill&quot;: {
        ///    &quot;en&quot;: {
        ///      &quot;text&quot;: &quot;Time to kill&quot;
        ///    }
        ///  },
        ///  &quot;distancePlayer&quot;: {
        ///    &quot;en&quot;: {
        ///      &quot;text&quot;: &quot;Distance to player&quot;
        ///    }
        ///  },
        ///  &quot;distanceMouse&quot;: {
        ///    &quot;en&quot;: {
        ///      &quot;text&quot;: &quot;Distance to mouse&quot;
        ///    }
        ///  },
        ///  &quot;dealsMostDmg&quot;: {
        ///    &quot;en&quot;: {
        ///      &quot;text&quot;: &quot;Deals most damage&quot; 
        ///    } 
        ///  }
        ///}.
        /// </summary>
        internal static string TargetSelector {
            get {
                return ResourceManager.GetString("TargetSelector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;en&quot;: {
        ///    &quot;text&quot;: &quot;Built-in utilities&quot;,
        ///    &quot;helpText&quot;: &quot;All the goodies, just a click away!&quot;
        ///  },
        ///  &quot;zh&quot;: {
        ///    &quot;text&quot;: &quot;??&quot;,
        ///    &quot;helpText&quot;: &quot;??&quot;
        ///  },
        ///  &quot;active&quot;: {
        ///    &quot;en&quot;: {
        ///      &quot;text&quot;: &quot;Enabled utilities&quot;
        ///    },
        ///    &quot;zh&quot;: {
        ///      &quot;text&quot;: &quot;??&quot;
        ///    },
        ///    &quot;activator&quot;: {
        ///      &quot;en&quot;: {
        ///        &quot;text&quot;: &quot;Enable activator&quot;
        ///      },
        ///      &quot;zh&quot;: {
        ///        &quot;text&quot;: &quot;??&quot;
        ///      }
        ///    },
        ///    &quot;indicator&quot;: {
        ///      &quot;en&quot;: {
        ///        &quot;text&quot;: &quot;Enable damage indicator&quot;
        ///      },
        ///      &quot;zh [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Utilities {
            get {
                return ResourceManager.GetString("Utilities", resourceCulture);
            }
        }
    }
}
