//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SparkTech.SDK.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SparkTech.SDK.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Banner {
            get {
                object obj = ResourceManager.GetObject("Banner", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;en&quot;: {
        ///    &quot;text&quot;: &quot;Surgical.SDK&quot;,
        ///    &quot;helpText&quot;: &quot;Here you will find all the settings that impact other scripts&quot;
        ///  },
        ///  &quot;zh&quot;: {
        ///    &quot;text&quot;: &quot;Surgeon制作&quot;,
        ///    &quot;helpText&quot;: &quot;帮助&quot;
        ///  },
        ///  &quot;language&quot;: {
        ///    &quot;en&quot;: {
        ///      &quot;text&quot;: &quot;Language&quot;
        ///    },
        ///    &quot;zh&quot;: {
        ///      &quot;text&quot;: &quot;语言 (language)&quot;
        ///    }
        ///  },
        ///  &quot;menu&quot;: {
        ///    &quot;en&quot;: {
        ///      &quot;text&quot;: &quot;Menu settings&quot;
        ///    },
        ///    &quot;zh&quot;: {
        ///      &quot;text&quot;: &quot;Menu settings ??&quot;
        ///    },
        ///    &quot;key&quot;: {
        ///      &quot;en&quot;: {
        ///        &quot;text&quot;: &quot;Activation button&quot;
        ///      },
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MainMenu {
            get {
                return ResourceManager.GetString("MainMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] RenderEffectCompiled {
            get {
                object obj = ResourceManager.GetObject("RenderEffectCompiled", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;en&quot;: {
        ///    &quot;keySelector&quot;: &quot;Press now...&quot;,
        ///    &quot;menuListEmpty&quot;: &quot;Less than 2 options provided&quot;,
        ///    &quot;firstTimeWelcome&quot;: &quot;Welcome to {platform}!\nEnglish language detected.\nYou can change that in the menu.&quot;,
        ///
        ///    // special, don&apos;t translate, only change here
        ///    &quot;languageUnknown&quot;: &quot;Welcome to {platform}!\nYour system language,\n\&quot;{language}\&quot; is not supported by the SDK.\nDefault will be used.\nYou can change that inside the menu.&quot;
        ///  },
        ///  &quot;zh&quot;: {
        ///
        ///  } 
        ///}.
        /// </summary>
        internal static string Strings {
            get {
                return ResourceManager.GetString("Strings", resourceCulture);
            }
        }
    }
}
